import { addDoc, collection, doc, getDocs, query, where, updateDoc, deleteDoc, serverTimestamp } from "firebase/firestore";
import { db, auth } from "../firebase";

// Adding user stations 
// with autogenerated id (what if user creates few stations with the same name)
// ownership (who created stations, so firestore rules specify what only owner can do, check them for details)
// creation and update timestamps
export async function addUserStation({ name, latitude, longitude, country }) {
  const user = auth.currentUser;
  if (!user) throw new Error("Login required");

  const payload = { 
    name,
    latitude,
    longitude,
    country,
    ownerId: user.uid,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  };

  const ref = await addDoc(collection(db, "userStations"), payload);
  return { id: ref.id, ...payload };
}


try {
    const q = query(collection(db, "stations"), orderBy("name"));

    const snapshot = await getDocs(q);
    return snapshot.docs.map(doc => ({ id: doc.id,...doc.data()}));
  } catch (e) {
    console.error("Error fetching sorted stations:", e);
    return [];
  }